spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simple-webapp
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: localhost
    port: 1025
