spring:
  application:
    name: simple-webapp
  modulith:
    events:
      completion-mode: archive
      jdbc:
        schema-initialization:
          enabled: false
    runtime:
      flyway-enabled: true

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  mail:
    from: ${MAIL_FROM:noreply@example.com}

logging:
  level:
    org.jooq.Constants: WARN


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - modulith